# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # Depend on Centos 7.6.1810
  config.vm.box = 'centos/7'

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 4
  end

  config.vagrant.plugins = ['vagrant-vbguest']
  config.vbguest.auto_update = false

  # When disabling inserting key, vagrant will use `~/.vagrant.d/insecure_private_key` to connect to
  # this box, and the final packaged box will contain the corresponding public key, so new boxes created
  # from this base box by default will have insecure pair of ssh key replaced with a new pair of ssh key.
  # Ref: https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-insert_key
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  ## Uncomment this when you want to ssh into the box using your private key.
  ## Another way is to use agent forwarding `vagrant ssh somebox -- -A`.
  # pubkey_path = File.expand_path('~/.ssh/id_rsa.pub')
  # if File.exists?(pubkey_path)
  #   pubkey = File.read(pubkey_path).chomp
  #   config.vm.provision :shell, inline: <<-SHELL
  #     echo "#{pubkey}" >> /home/vagrant/.ssh/authorized_keys
  #   SHELL
  # end

  env = {}
  ENV.each { |k, v| env[k] = v if k.start_with?('SETUP_') }
  config.vm.provision :shell, path: 'setup', privileged: false, env: env
end
