# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # Depend on Centos 7.6.1810
  config.vm.box = 'centos/7'

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 4
  end

  config.vagrant.plugins = ['vagrant-vbguest']
  config.vbguest.auto_update = false

  # When disabling inserting key, vagrant will use `~/.vagrant.d/insecure_private_key` to connect to
  # this box, and the final packaged box will contain the corresponding public key, so new boxes created
  # from this base box by default will have insecure pair of ssh key replaced with a new pair of ssh key.
  # Ref: https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-insert_key
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  ## Uncomment this when you want to ssh into the box using your private key.
  ## Another way is to use agent forwarding `vagrant ssh somebox -- -A`.
  # config.vm.provision :shell, inline: <<-SHELL
  #   cat ~/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  # SHELL

  config.vm.provision :shell, inline: <<-SHELL
    # Allow ssh password authentication.
    sed -i 's/^PasswordAuthentication no$/PasswordAuthentication yes/' /etc/ssh/sshd_config

    rm /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    echo 'export LANG=en_US.UTF-8' >/home/vagrant/.zshenv.pre.local && chown vagrant:vagrant /home/vagrant/.zshenv.pre.local
  SHELL

  config.vm.provision :ansible do |ansible|
    ansible.playbook = '../ansible_playbooks/dotfiles.yml'
    ansible.groups = { dotfiles: ['default'] }
    if (proxy = ENV['PROXY']) && !proxy.empty?
      git_http_proxy = "http://#{proxy}"
      git_https_proxy = "https://#{proxy}"
      curl_proxy = proxy
    end
    ansible.extra_vars = {
      zsh: { version: '5.8', chsh: true, password: 'vagrant' },
      nvim: { version: '0.3.8', install_from_source: false },
      git_http_proxy: git_http_proxy,
      git_https_proxy: git_https_proxy,
      curl_proxy: curl_proxy,
    }
    ansible.verbose = true
    if (tags = ENV['TAGS']) && !tags.empty?
      ansible.tags = tags
    end
  end
end
